# Generated by Django 5.1.3 on 2025-03-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_repudiation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_format',
            field=models.TextField(null=True),
        ),
    ]

